---

devilbox_info:
    name: swagger
    description: Swagger-API tools
    author: "Laurent Laville"
    github: llaville
    license: MIT
    min_devilbox_version: v1.0.1
    tags:
        - swagger
        - OpenAPI
