---

devilbox_info:
  name: webgrind
  description: Xdebug Profiling Web Frontend in PHP
  author: "Laurent Laville"
  github: llaville
  license: MIT
  min_devilbox_version: v1.0.1
  tags:
    - Xdebug
    - Profiling
    - GUI
